### ISSUE TITLE
Typescript version of this project

### ISSUE THREAD

**Issue by sowsan** [philnash/twilio-video-react-hooks#45] opened 2021-02-23 23:09 UTC
Thank you for producing this sample. I am new to Typescript and building an app and learning. Is there a typescript version available for the same? I am getting a bunch of errors on types after converting few files from JS to TSX. Thanks for your comments.

**Comment by philnash** [comment] 2021-02-23 23:53
There is not a TypeScript version of this. I've not tried converting it myself, but if you share your errors, I might be able to help.

**Comment by sowsan** [comment] 2021-02-24 01:59
Thank you so much @philnash . I am pretty sure that, I am missing some fundamental concepts in TS... I just converted the VideoChat.js to VideoChat.tsx using react-js-to-ts ./src/VideoChat.js and below are the errors.

![image](https://user-images.githubusercontent.com/11544153/108933807-c8cbee00-7619-11eb-885f-e61c3abafba3.png)

Full script goes here...

```
import React, { useState, useCallback, useEffect } from "react";
import Video from "twilio-video";
import Lobby from "./Lobby";
import Room from "./Room";

const VideoChat = () => {
  const [username, setUsername] = useState("");
  const [roomName, setRoomName] = useState("");
  const [room, setRoom] = useState(null);
  const [connecting, setConnecting] = useState(false);

  const handleUsernameChange = useCallback((event) => {
    setUsername(event.target.value);
  }, []);

  const handleRoomNameChange = useCallback((event) => {
    setRoomName(event.target.value);
  }, []);

  const handleSubmit = useCallback(
    async (event) => {
      event.preventDefault();
      setConnecting(true);
      const data = await fetch("/video/token", {
        method: "POST",
        body: JSON.stringify({
          identity: username,
          room: roomName,
        }),
        headers: {
          "Content-Type": "application/json",
        },
      }).then((res) => res.json());
      Video.connect(data.token, {
        name: roomName,
      })
        .then((room) => {
          setConnecting(false);
          setRoom(room);
        })
        .catch((err) => {
          console.error(err);
          setConnecting(false);
        });
    },
    [roomName, username]
  );

  const handleLogout = useCallback(() => {
    setRoom((prevRoom) => {
      if (prevRoom) {
        prevRoom.localParticipant.tracks.forEach((trackPub) => {
          trackPub.track.stop();
        });
        prevRoom.disconnect();
      }
      return null;
    });
  }, []);

  useEffect(() => {
    if (room) {
      const tidyUp = (event) => {
        if (event.persisted) {
          return;
        }
        if (room) {
          handleLogout();
        }
      };
      window.addEventListener("pagehide", tidyUp);
      window.addEventListener("beforeunload", tidyUp);
      return () => {
        window.removeEventListener("pagehide", tidyUp);
        window.removeEventListener("beforeunload", tidyUp);
      };
    }
  }, [room, handleLogout]);

  let render;
  if (room) {
    render = (
      <Room roomName={roomName} room={room} handleLogout={handleLogout} />
    );
  } else {
    render = (
      <Lobby
        username={username}
        roomName={roomName}
        handleUsernameChange={handleUsernameChange}
        handleRoomNameChange={handleRoomNameChange}
        handleSubmit={handleSubmit}
        connecting={connecting}
      />
    );
  }
  return render;
};

export default VideoChat;
```

**Comment by philnash** [comment] 2021-02-24 02:31
The issue is that `useState` needs to know what type it is supposed to be used with. [This blog post has a good description of what is going on](https://www.carlrippon.com/typed-usestate-with-typescript/).

This only happens for the room because the initial `useState` is called with `null` so TypeScript can't infer anything else about it. Other `useState`s use empty strings as their initial values, so when you set them with a non-empty string there isn't a change of type.

To fix this, I think you need to tell `useState` what types it can have, in this case `null` and `Video.Room`.

```typescript
  const [room, setRoom] = useState<Video.Room | null>(null);
```

That should fix the other things you circled in the screenshot too. Except perhaps the `trackPub`, if that is still a problem let me know.

**Comment by sowsan** [comment] 2021-02-24 03:45
Thank you so much, yes the room object issue was resolved by adding the type...

There are two more errors not sure if it is related to the Twilio Video SDK.. I am using,  "twilio-video": "^2.12.0"

trackPub

![image](https://user-images.githubusercontent.com/11544153/108944309-7c3bdf00-7628-11eb-93c0-ae2cf03e8786.png)

![image](https://user-images.githubusercontent.com/11544153/108944403-a8576000-7628-11eb-9528-b952ee774657.png)
More details..

BeforeUnloadEvent' but required in type '{ persisted: any; }'.
  Overload 2 of 2, '(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions | undefined): void', gave the following error.
    Argument of type '(event: {    persisted: any;}) => void' is not assignable to parameter of type 'EventListenerOrEventListenerObject'.
      Type '(event: {    persisted: any;}) => void' is not assignable to type 'EventListener'.
        Types of parameters 'event' and 'evt' are incompatible.
          Property 'persisted' is missing in type 'Event' but required in type '{ persisted: any; }'.ts(2769)
VideoChat.tsx(61, 32): 'persisted' is declared here.
VideoChat.tsx(61, 32): 'persisted' is declared here.

Also was using this to fix an error

 useEffect(() => {
    if (room) {
      **const tidyUp = (event: { persisted: any; }) => {**
        if (event.persisted) {

**Comment by philnash** [comment] 2021-02-24 23:34
The first error there is because `localParticipant.tracks` can produce a list of `LocalVideoTrack`, `LocalAudioTrack` and `LocalDataTrack` and as the error says `LocalDataTrack` doesn't have a `stop` function.

You could maybe do something like:

```typescript
prevRoom.localParticipant.tracks.forEach(trackPub => {
  if (trackPub.track.stop) {
    trackPub.track.stop();
  }
})
```

For the second error, the issue is that we are using one function to listen to two events that are different types.

I think you might be able to fix it by telling the `tidyUp` function to expect both types of events, like this:

```typescript
const tidyUp = (event: BeforeUnloadEvent | PageTransitionEvent) => {
```

**Comment by sowsan** [comment] 2021-02-25 02:21
Thank you @philnash. I will check it. I saw a project on TS here https://github.com/twilio/twilio-video-app-react but I felt like it is a bit complicated for my scenario. It would be great if we can have a simplified TS sample for the exact scenario that you have using react hooks. Do you know any samples available from Twilio which covers this scenario in TSX?

**Comment by philnash** [comment] 2021-02-25 03:09
Hey @sowsan, I don't know of a TypeScript version of this project. If you are learning TypeScript, then moving a project over to TypeScript is great practice to get to know the type system and how to solve type problems when you have a JS example.

Did you try the two answers above and did they work at all?

**Comment by sowsan** [comment] 2021-02-25 03:12
Got it, thank you so much. Yes that worked. There are bunch of other issues and I believe most of them related to type declarations. I will work on it as you said and will see 🙏👍

**Comment by philnash** [comment] 2021-02-25 03:59
Awesome, good luck with the rest of the type issues. If you get stuck, let me know and I'll do my best to help (though I can't promise anything!).

I'll close this issue for now, if you have further problems, please feel free to re-open.

**Closed as completed by philnash** 2021-02-25 03:59 UTC
