### ISSUE TITLE
Adding to a production Next.js web app

### ISSUE THREAD

**Issue by rhtaylor** [philnash/twilio-video-react-hooks#65] opened 2021-11-13 18:51 UTC
Thanks for the great resource. It works well in isolation with your repo. 

If I want to add the principals you are using do I need to add the proxy I see in package.json 
`"proxy": "http://localhost:3001/",
  "eslintConfig": {
    "extends": "react-app"
  },` 

What about the server directory you have in your repo?  

I am working on a Next.js production web app and there is some information needed to get this up and running. 

post edit: After finding more of your resources and even a [video](https://www.youtube.com/watch?v=inx4ZqsHMtA) I decided to build out the functionality from scratch and hope for the best.

**Comment by philnash** [comment] 2021-11-14 22:27
Hey @rhtaylor, it likely is best to build out the functionality yourself using this and other repos as examples. That way you will understand how your app works and be able to build the functionality you want.

Just as a note, the `proxy` key here is so that I can run both an Express server and the React front end and have React be able to talk to the server through the same host/port number that it runs on. I talk more about how that works in [this blog post](https://www.twilio.com/blog/react-app-with-node-js-server-proxy). This is done so that the server side can generate the access token for the application.

Since you are building with Next you can use [API routes](https://nextjs.org/docs/api-routes/introduction) to generate and return access tokens and you don't need a separate server directory or proxy to do that.

I'll close this issue for now, but let me know if you come across any other issues when building this out.

**Closed as completed by philnash** 2021-11-14 22:27 UTC

**Comment by rhtaylor** [comment] 2021-11-18 01:42
Thank you for response. Unfortunately the app runs on Next@8 before the api routes were implemented. I was attempting to hit the rails backend from the front. I had a lot of success creating a twilio JWT token. However I am unable to send it back to the frontend. I tells me max call stack exceeded. What information from the token do I need to get authorization to connect to a room? Perhaps I could parse out the needed info and send it back through the rails api?

**Comment by philnash** [comment] 2021-11-18 02:51
Ah, ok, you have a Rails back-end for this. You need the entire token in the front-end to use it. Can you share how you are creating the token in the Rails app and how you are fetching it from the front-end? Also, where are you exceeding the max call stack, front or back end?

**Comment by rhtaylor** [comment] 2021-11-18 05:33
The app uses redux to dispatch an action that calls the front-end api to the rails backend with a post request. I'm using your tutorial and giving a form to create a room name. The person's identity is pulled out of state.  On submission of the form you call the api which dispatches the action:

    export const getTwilioToken = (twilioAuthBody) => ({ 
      [CALL_API]: {
      types: [TWILIO_REQUEST, TWILIO_SUCCESS, TWILIO_FAILURE ],
      endpoint: 'users/twilio',
      method: HTTP_METHODS.POST, 
      body: {twilioAuthBody} 
      },
    })

This Post request hits the rails backend in a controller action I named twilio. I did not create a twilio controller like I have seen in texting twilio tutorial's.  
In the user's controller the action is :

    def twilio 
        @token = Twilio::JWT::AccessToken.new(ENV['ACCOUNT_SID'], ENV['TWILIO_API_KEY_SID'],ENV['TWILIO_API_SECRET'], 
         identity: identity)
         render json: @token
    end

Very simple and this will return the twilio token object without the stack error. The stack error was when I was attempting to send the room object itself back. 

twilio token example: 

     account_sid: null
     algorithm: "HS256"
     grants: []
     identity: ""
     issuer: "SK5e23f58c7365739e4714e81ee3e34fc9"
     nbf: null
     region: null
     secret: "Pr2gLPP6CmiK7U1qUEaGx5gsYWbQP5MX"
     secret_key: "Pr2gLPP6CmiK7U1qUEaGx5gsYWbQP5MX"
     signing_key_sid: "SK5e23f58c7365739e4714e81ee3e34fc9"
     subject: null
     ttl: 3600
      valid_until: null
     [[Prototype]]: Object

This will return and get converted into json through the api and put into local state with redux and mapStateToProps. 
I then attempt to connect to the room: 

     Video.connect(response, {
            name: roomName,
          })
            .then((room) => {
              setConnecting(false);
              setRoom(room);
            })
            .catch((err) => {
              console.error(err);
              setConnecting(false);
             });
         },
    [     roomName,, token]
       )  ;


I attempt to use this as the token (response is the token) to start the room and I get the error `token must be a string` I am thinking that possibly this should be converted into a JWT format. 


I haven't found tutorials for a rails api and I will attempt to write a post on this when I get it working. 

Again ty for the help!

**Comment by philnash** [comment] 2021-11-18 06:40
I think the issue is within your controller action, which is currently:

```ruby
def twilio 
  @token = Twilio::JWT::AccessToken.new(
    ENV['ACCOUNT_SID'],
    ENV['TWILIO_API_KEY_SID'],
    ENV['TWILIO_API_SECRET'],
    identity: identity
  )
  render json: @token
end
```

Firstly, you need to provide a video grant to this token so that it will grant access to the Video service. Next, you're returning the token object as a JSON object, but it needs to be converted to a token. Once it is a token, it is just a string, so wrap it in a hash so you can return it as JSON.

[The documentation for generating a token for a Video room and a Ruby example is here.](https://www.twilio.com/docs/iam/access-tokens?code-sample=code-creating-an-access-token-video&code-language=Ruby&code-sdk-version=5.x)

Try changing your action to this:

```ruby
def twilio 
  @token = Twilio::JWT::AccessToken.new(
    ENV['ACCOUNT_SID'],
    ENV['TWILIO_API_KEY_SID'],
    ENV['TWILIO_API_SECRET'],
    identity: identity
  )

  grant = Twilio::JWT::AccessToken::VideoGrant.new
  @token.add_grant(grant)

  render json: { token: @token.to_jwt }
end
```

Then, in your front-end you'll need to parse the response as JSON and then extract the token from the JSON object to use in `Video.connect`.

Let me know how you get on with that.

**Comment by rhtaylor** [comment] 2021-11-18 07:03
Ty. Glad there are people out there like you creating the future.

**Comment by philnash** [comment] 2021-11-18 10:50
Did that work for you then?

And hey, you're the one building the application, that's the future I want to see created! If there's anything else I can do to help, let me know.

**Comment by rhtaylor** [comment] 2021-11-18 18:10
It's working beautifully and I'm so happy. It's a video chat for the company I work for. They needed a way to run orientation videos for newly hired workers. The business is a PAAS that connects workers to businesses that need workers. 
Again ty

**Comment by philnash** [comment] 2021-11-18 23:46
That's awesome, and a great use case for it! Glad it is working out!
